=== lmstudio-ai/lmstudio.js/scaffolds/scaffold-json-schema-v1.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["scaffoldVersion", "name", "displayName", "description", "args", "motd"],
  "properties": {
    "scaffoldVersion": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "args": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "default"],
        "properties": {
          "name": {
            "type": "string"
          },
          "replaceFrom": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "default": {
            "type": "string"
          },
          "isProjectName": {
            "type": "boolean"
          }
        }
      }
    },
    "renames": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["from", "to"],
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        }
      }
    },
    "motd": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["text"],
        "properties": {
          "type": {
            "type": "string",
            "enum": ["regular", "title", "command", "hint"]
          },
          "text": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== lmstudio-ai/lmstudio.js/scaffolds/node-typescript/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-typescript",
  "displayName": "Node.js with TypeScript",
  "description": "Example Node.js TypeScript project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-typescript",
      "replaceFrom": ["@lmstudio/scaffold-node-typescript", "<PROJECT_NAME>"],
      "isProjectName": true
    },
    {
      "name": "Author",
      "default": "",
      "replaceFrom": ["<AUTHOR>"]
    }
  ],
  "renames": [{ "from": "gitignore_template", "to": ".gitignore" }],
  "motd": [
    { "type": "title", "text": "âœ“ Project Creation Successful" },
    {
      "type": "regular",
      "text": "An example Node.js TypeScript project with lmstudio.js has been created in the <hl><PROJECT_NAME></hl> folder. You can enter it with:"
    },
    { "type": "command", "text": "cd <PROJECT_NAME>" },
    { "type": "regular", "text": "Then you can run the project with:" },
    { "type": "command", "text": "lms server start\nnpm start" }
  ]
}

=== lmstudio-ai/lmstudio.js/scaffolds/node-javascript-empty/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-javascript-empty",
  "displayName": "Node.js with JavaScript (Empty)",
  "description": "Minimalistic Node.js JavaScript empty project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-javascript-empty",
      "replaceFrom": ["@lmstudio/scaffold-node-javascript-empty", "<PROJECT_NAME>"],
      "isProjectName": true
    }
  ],
  "renames": [{ "from": "gitignore_template", "to": ".gitignore" }],
  "motd": [
    { "type": "title", "text": "âœ“ Project Creation Successful" },
    {
      "type": "regular",
      "text": "An empty Node.js JavaScript project with lmstudio.js has been created in the <hl><PROJECT_NAME></hl> folder. You can enter it with:"
    },
    { "type": "command", "text": "cd <PROJECT_NAME>" },
    { "type": "regular", "text": "Then you can run the project with:" },
    { "type": "command", "text": "lms server start\nnpm start" }
  ]
}

=== lmstudio-ai/lmstudio.js/scaffolds/node-javascript/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-javascript",
  "displayName": "Node.js with JavaScript",
  "description": "Example Node.js JavaScript project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-javascript",
      "replaceFrom": ["@lmstudio/scaffold-node-javascript", "<PROJECT_NAME>"],
      "isProjectName": true
    }
  ],
  "renames": [{ "from": "gitignore_template", "to": ".gitignore" }],
  "motd": [
    { "type": "title", "text": "âœ“ Project Creation Successful" },
    {
      "type": "regular",
      "text": "An example Node.js JavaScript project with lmstudio.js has been created in the <hl><PROJECT_NAME></hl> folder. You can enter it with:"
    },
    { "type": "command", "text": "cd <PROJECT_NAME>" },
    { "type": "regular", "text": "Then you can run the project with:" },
    { "type": "command", "text": "npm start" }
  ]
}

=== lmstudio-ai/lmstudio.js/scaffolds/node-typescript-empty/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-typescript-empty",
  "displayName": "Node.js with TypeScript (Empty)",
  "description": "Minimalistic Node.js TypeScript empty project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-typescript-empty",
      "replaceFrom": ["@lmstudio/scaffold-node-typescript-empty", "<PROJECT_NAME>"],
      "isProjectName": true
    },
    {
      "name": "Author",
      "default": "",
      "replaceFrom": ["<AUTHOR>"]
    }
  ],
  "renames": [{ "from": "gitignore_template", "to": ".gitignore" }],
  "motd": [
    { "type": "title", "text": "âœ“ Project Creation Successful" },
    {
      "type": "regular",
      "text": "An empty Node.js TypeScript project with lmstudio.js has been created in the <hl><PROJECT_NAME></hl> folder. You can enter it with:"
    },
    { "type": "command", "text": "cd <PROJECT_NAME>" },
    { "type": "regular", "text": "Then you can run the project with:" },
    { "type": "command", "text": "npm start" }
  ]
}

=== lmstudio-ai/lmstudio.js/scaffolds/node-typescript-preprocessor/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-typescript-preprocessor",
  "displayName": "Prompt Preprocessor with TypeScript",
  "description": "Example prompt preprocessor implemented TypeScript.",
  "args": [
    {
      "name": "Project Name",
      "default": "node-typescript-preprocessor",
      "replaceFrom": ["@lmstudio/scaffold-node-typescript-preprocessor", "<PROJECT_NAME>"],
      "isProjectName": true
    }
  ],
  "renames": [{ "from": "gitignore_template", "to": ".gitignore" }],
  "motd": [
    { "type": "title", "text": "âœ“ Project Creation Successful" },
    {
      "type": "regular",
      "text": "An example Prompt Preprocessor TypeScript project with lmstudio.js has been created in the <hl><PROJECT_NAME></hl> folder. You can enter it with:"
    },
    { "type": "command", "text": "cd <PROJECT_NAME>" },
    { "type": "regular", "text": "Then you can run the project with:" },
    { "type": "command", "text": "lms server start\nnpm start" }
  ]
}
